### ISSUE TITLE
IE 11 with NTLM not giving a user.

### ISSUE THREAD

**Issue by merpnderp** [abbr/NodeSSPI#15]
Hello, I'm not getting a user object on req.connection when connecting with IE11. I'm using NTLM and all the default settings. IE11 prompts me for a username and password (I don't think it should) and then the authenticate callback is called with no error, but also no username. With Chrome and Firefox it works perfectly (I'm prompted for a username and password as I should be).

Is this a bug or am I doing something wrong?

**Comment by abbr** [comment]
Can you see if you get same problem if using an earlier version of NodeSSPI, such as v0.1.9 or 0.1.10?

**Comment by merpnderp** [comment]
Same issues with 0.1.9 and 0.1.10.

**Comment by merpnderp** [comment]
Is there a way to get debug info of some sort that might help explain what is going on?

**Comment by abbr** [comment]
Which Node version do you use? I can only confirm basic authentication (by setting `offerSSPI` to false) doesn't work on latest version of node-sspi with IE 11.
It's not a bug for NTLM prompting for login. You have to add the url (http://localhost:3000 in the example) to your local intranet zone to avoid it.

**Comment by merpnderp** [comment]
It looks like my problems were some sort of IE11 caching. I'm really not sure what I changed as I had retried the connection many times, and rebooted several times also. But after hitting ctrl-f5 many times in frustration it just started to work. And now I can't get it to not work. Very perplexing and disconcerting because now I don't know if I'll deploy it to production and it will start randomly failing for users.

But thank you for looking into this. The code works perfectly. My ability to figure out how to get IE11 to auth was the problem. And I have no idea how I fixed it except opening up dev tools, recording network traffic, and pounding ctrl-f5 (which I'd done many times before).

**Comment by abbr** [comment]
If your AD domain user/group data is in English and you can use Node 0.12 or earlier, then node-sspi@0.1.8 is probably more stable for prod. Latest 3 releases may still have couple bugs due to the amount of code change in order to support Node 4 and multi-byte characters.

**Comment by merpnderp** [comment]
Thanks a lot for your help abbr. If I have any more issues, I'll drop back to 1.8. I'm currently on node 0.12.7 with node-sspi 0.1.10 working. If I can do any testing for you with this set up, please let me know.

**Comment by abbr** [comment]
The issue I have confirmed not working in IE11 is due to basic authentication not having character encoding standardized. For details, see this [stackoverflow question](http://stackoverflow.com/questions/702629/utf-8-characters-mangled-in-http-basic-auth-username). `node-sspi` assumes user name/password is utf-8 encoded, which IE doesn't comply. Therefore to allow non-ascii encoded name/password, avoid using basic authentication. NTLM, however, works.
