### ISSUE TITLE
Compatibility with node v 4 / gyp

### ISSUE THREAD

**Issue by christopherhardie1** [abbr/NodeSSPI#17]
Hi ,
I am having major trouble in trying to install node-sspi with node V4. There seems to be compatibility issues between node and gyp similar to the ones listed in the link that I have included here. Has anyone else experienced this?
Thanks very much.

first let me say what a great job you have done with node-sspi, there is nothing else out there for node like it!

https://www.robertkehoe.com/2015/03/fix-node-gyp-rebuild-error-on-windows/

Chris.

**Comment by craigvl** [comment]
Yes I am also facing this problem on windows. Installs perfectly first time using node 0.12 but not with 4. I have many different combinations of Visual studio installations and command line parameters as suggested on different sites, and spent hours doing so. I have even tried different Windows OS (server 2012, windows 7 and windows 10).  Has anyone else been able to install this package in node version 4? Even if someone could confirm that it is possible that would be great so I can know if it is worth keeping trying or not. I really want to use this package in v4 (i second that this package is awesome work, well done abbr !!).   Thanks so much.

**Comment by abbr** [comment]
I'll work on a new release. In the meanwhile you have a couple options:
1. use Node@4.0 (Avoid 4.1 and 4.2) which NodeSSPI comes with a pre-compiled binaries.
2. Install VS

**Comment by abbr** [comment]
Just published `node-sspi@0.1.12` with pre-compiled binaries for `Node@4.2` and `Node@5`

**Comment by christopherhardie1** [comment]
I just gave it a try and it works ! You are a genius. Thank you so much.
