### ISSUE TITLE
Made more generic for hapi

### ISSUE THREAD

**Issue by fritzy** [abbr/NodeSSPI#19]
It would be great if this package had functions which didn't touch the request/result objects directly so that I could use this with hapi. I could pull the needed values out of the request, send the needed replies, and just be returned an object with the user data.

**Comment by abbr** [comment]
I am not familiar with hapi, but can your requirement be met by saving req/res props before and restoring after calling NodeSSPI? Only a few props are changed by NodeSSPI as documented in output section. Also, setting `authoritative` option makes NodeSSPI even less intrusive.

**Comment by fritzy** [comment]
[hapi.js](http://hapijs.com/) is an http framework that is a lot more flexible than express, but has more structure. In any case, sending empty objects to NodeSSPI results in a segmentation fault. I ended up having to do something like this:

https://gist.github.com/fritzy/c5906e965bbcadabf47e

To emulate the objects that NodeSSPI expects from express. Ideally NodeSSPI would not rely on a specific JS module. I really appreciate your work and module though! :+1:

**Comment by abbr** [comment]
As documented `NodeSSPI` doesn't depend on Express. It only depends on Node, which supplies the  `request` and `response` input parameters. Express just provided a wrapper to these objects and is optional.

**Comment by fritzy** [comment]
Ah, sorry about that. Thanks.
