### ISSUE TITLE
Error compiling under Win7 32 bit

### ISSUE THREAD

**Issue by volkerhehl** [abbr/NodeSSPI#2]
Under Windows 7 32 bit with Visual Studio 2012 i got this error. I have no problems compiling other node.js modules in my environment. I think it's a problem with node-sspi itself!?

C:\Repos\test7>npm install node-sspi --msvs_version=2012

node-sspi@0.1.4 install C:\Repos\test7\node_modules\node-sspi
node ./build.js

debug=false
'win32-ia32-v8-3' exists; testing
Problem with the binary; manual build incoming

C:\Repos\test7\node_modules\node-sspi>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
Warning: Missing input files:
C:\Repos\test7\node_modules\node-sspi\build\..\src\*.cpp
C:\Repos\test7\node_modules\node-sspi\build\..\src\*.h
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  NodeSSPI.cpp
C:\Program Files\Microsoft Visual Studio 11.0\VC\include\xlocale(336): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc [C:\Repos\tes
t7\node_modules\node-sspi\build\NodeSSPI.vcxproj]
c:\repos\test7\node_modules\node-sspi\src\NodeSSPI.h(11): fatal error C1083: Cannot open include file: 'atlenc.h': No such file or directory [C:\Repos\test7\node_modules\node-sspi
\build\NodeSSPI.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:809:12)
gyp ERR! System Windows_NT 6.1.7600
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Repos\test7\node_modules\node-sspi
gyp ERR! node -v v0.10.29
gyp ERR! node-gyp -v v0.13.1
gyp ERR! not ok
Build failed
npm ERR! node-sspi@0.1.4 install: `node ./build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sspi@0.1.4 install script.
npm ERR! This is most likely a problem with the node-sspi package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sspi
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.1.7600
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "node-sspi" "--msvs_version=2012"
npm ERR! cwd C:\Repos\test7
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Repos\test7\npm-debug.log
npm ERR! not ok code 0

**Comment by pbininda** [comment]
The quick-test.js fails outside English locales. It checks for group `\\Everyone` which is called `\\Jeder` in German for example.

**Comment by abbr** [comment]
Thanks for the tip, @pbininda. Just published `node-sspi@0.1.5` to fix the bug.
