### ISSUE TITLE
User Pass prompt on IE and not working on chrome

### ISSUE THREAD

**Issue by Anahid** [abbr/NodeSSPI#20]
Hi,

I am using node-sspi to authenticate the windows username with a local database username. I am experiencing two issues: 

1.on some IE browsers, it prompts the user for their windows password and even when they mark as remember, they need to enter it again.

2. Also, it does not work in chrome. Can you please help me locate why that might be the case?

Many Thanks,

**Comment by abbr** [comment]
IE/Chrome skips password only if the site is in the trusted list, which could be a per-client config unless the client is in an AD domain which enforces group policy.
When you say "it does not work in chrome", do you mean chrome doesn't take password or it prompts for password?

**Comment by Anahid** [comment]
Many thanks for your reply! I really appreciate it :)

what I mean is that chrome does not ask for password so in my console I get
the err that Failed to load resource: the server responded with a status of
404 unaurhorized. but when i go to the samw url in IE it works fine.
also when i log the req.connection.user it is undefined in chrome but i get
the windows username in IE.

Do you know how i can fix this?

Thank you so much and warm regards,

Ana

**Comment by abbr** [comment]
Have you cleared cache in chrome?
Does the problem occur when you use the exact code I gave in the `README.md`?
