### ISSUE TITLE
Safari broken with backend SSPI

### ISSUE THREAD

**Issue by dankell** [abbr/NodeSSPI#22]
We're trying to integrate node-sspi into a backend express server and have been successful for all browsers except Safari (on iOS and Mac OS).

We have a bit more information here:

http://stackoverflow.com/questions/34225094/node-sspi-error-401-with-safari

As of today Chrome on iOS also seems to be broken - they have updated to use WKWebView so this may be the heart of the issue.

**Comment by abbr** [comment]
I have tried accessing a node-sspi protected site on latest iOS 9.2.1 using both safari and chrome all work fine. Earlier versions of iOS as I recall, especially safari, seemed to have difficulty handling ntlm auth. So the compatibility is improving, not worsening.

**Comment by dankell** [comment]
Hi abbr

Thanks for getting back to me. Safari is fine in the basic set up. 

The issue seems to be when there is a split with the backend and the front end. 

We're running an backend API server on port 
3301 and a front end server on Port 80 and that's when things break

I'm trying to reduce our site down to the barest bones so I can share what's happening. Might be early next week. 

I'm pretty sure Safari is the issue but my knowledge is minimal.

**Comment by dankell** [comment]
We've confirmed that basic NodeSSPI setup works fine for us with iOS 9.2.1. 

We've trimmed our site right down and have uploaded a copy to github [here ](https://github.com/dankell/BareSSPI)

The bug occurs in `/api/config/express.js` in the following code:
`app.use(function (req, res, next) {`
`     if (req.url === '/api/app/user/ldap/authenticate') {`
`        sspiObj.authenticate(req, res, function (err) {`
`            if (err)`
`                console.log(err);`
`            console.log(res.finished);`
`            res.finished || next();`
`        });`
`    } else {`
`        next();`
`    }`
`});`
When we look at the logging a Domain PC calls the above code 3 times before authenticating. res.finished logs _true, true, false_

Chrome on Mac OS makes 3 calls, and on the second call pops up the (system) User Authentication dialog.

Safari on Mac OS, and Chrome and Safari on iOS both fail to pop up the login dialog instead reporting an `error 401` at the point you would see the dialog.

It's either a) something we are doing wrong, or b) a bug in Safari. Chrome was working before it switched to WKWebView

**Comment by abbr** [comment]
Instead of pointing me to your full-blown web app, can you narrow down the problem to node-sspi by running the code I gave in my `readme.md` on your host?
Also, can you confirm it's NTLM protocol that gives your error 401? What I have tested earlier is NTLM works for safari on iOS 9.2.1.

**Comment by dankell** [comment]
As I said the default setup, as in readme.md works. The issue occurs when we split the frontend and backend, as in the uploaded example.

We think that the issue is with how WKWebview handles CORS resources, however we would like help trying to pin down how node-sspi should be causing the browser to request Authentication details (i.e. presenting a login/password dialog)

**Comment by abbr** [comment]
Then it becomes obvious the problem is not in `node-sspi`. This forum is intended for `node-sspi`, not for troubleshooting your application problems, so I have to close the ticket.
Having said that, I skimmed your code and concur CORS is likely the cause. Couple things you might try:
1. relax restrictions such as allowed headers
2. your limited method to GET, but pre-flight uses OPTIONS. You need to give more thoughts to pre-flight, whose implementation is browser dependent.
