### ISSUE TITLE
curl authenticate

### ISSUE THREAD

**Issue by arieljannai** [abbr/NodeSSPI#25]
Hi,

Do you know how can I authenticate in front of the server using `node-sspi` with curl?
I want the curl to take the connected user credentials
I've tried `curl --ntlm -u : http://site` and also with negotiate but I keep getting `Login aborted` (401), unless of course I pass the user with `curl --ntlm -u username http://site`

Do you know how to accomplish that?

**Comment by abbr** [comment]
This forum is about NodeSSPI and your question is a little off the topic unless you can confirm your command works for other NTLM sites not implemented by NodeSSPI.
