### ISSUE TITLE
Auth prompt when not using localhost

### ISSUE THREAD

**Issue by gcraftyg** [abbr/NodeSSPI#27]
We are using the default settings of node-sspi as outlined on the readme.

When running the app from http://localhost/appname we are successfully logged in, without a prompt for credentials. 

As soon as we request the app from the domain name, http://domainname.com/appname, we are no longer automatically logged in and are prompted to enter our auth credentials.

**Comment by abbr** [comment]
This is not a problem of node-sspi. http://domainname.com has to be trusted by browser to support transparent NTLM authentication. How to let browser trust the host depends on browser. For IE and Chrome, it is either set by your AD admin via GPO or you can add the host to local intranet zone.

**Comment by ShonP** [comment]
@abbr I'm facing same issue. couldn't understand what should I do to fix it. why when using web api windows auth of .net it doesn't prompt for credentials and automaticly logged in, and while using express with node-sspi it asks for credentials. (happens only when I deploy my app to iis, in localhost it works fine).

**Comment by f-w** [comment]
@ShonP , if you hit remote node-sspi instance directly with browser, do you get login prompt? Also, if using windows client, have you added the api domain to trusted intranet zone?

**Comment by abbr** [comment]
@ShonP , if you hit remote node-sspi instance directly with browser, do you get login prompt? Also, if using windows client, have you added the api domain to trusted intranet zone?
