### ISSUE TITLE
Is there a way to buy you a beer?

### ISSUE THREAD

**Issue by denkan** [abbr/NodeSSPI#28]
Just got by this repo as I was fumbling trying to pipe an IIS Windows Authentication to a NodeJS solution. And I just had to express my appreciation - a star simply isn't enough this time. 

Really like your work and I think you've cracked a cornerstone when targeting mid-to-large sized, MS/.NET loving corporations, used to be integrated with ADs etc.

Pass me a Paypal link or likewise and I'll buy you a well-deserved beer.

**Comment by abbr** [comment]
Glad you find NodeSSPI useful and appreciate your kindness. My Paypal acct is wenfred@gmail.com
