### ISSUE TITLE
Users share authentication behind reverse proxy

### ISSUE THREAD

**Issue by baseless** [abbr/NodeSSPI#30]
Adds this as a separate issue (mentioned it in an earlier issue). It seems that when placing node-sspi application behind a reverse-proxy (ARR3 or httpplatformhandler in IIS is what i used) users start sharing each others authentication if usePerRequest is set to false.

Based on the [earlier mentioned sample project](https://github.com/baseless/sspi_sample) i tried adding 'app.set('trust proxy', true);' to express. But this do not seem to help unfortunatly. Do you happen to know what is required for node-sspi to work reliably behind a reverse proxy?

**Comment by abbr** [comment]
When Node is behind rp the connection is multiplexed so it's an expected behavior. But in such case NodeSSPI shouldn't be used in first place. Instead, let IIS perform the authentication. So it's a non-issue.

**Comment by baseless** [comment]
Thanks a lot for the input! The thought of letting IIS handle it in the case of utilizing iis occured to me but, due to some pheriphical circumstances, i thought it was worth asking.
