### ISSUE TITLE
Running without Express - Help Wanted

### ISSUE THREAD

**Issue by dee342** [abbr/NodeSSPI#31]
"Express.js, NodeSSPI doesn't have to be run under the context of Express.js"

I am trying to run NodeSSPI with Electron and need to run it without Express.js.  Can someone tell me how to do that?  Thank you.

**Comment by abbr** [comment]
NodeSSPI is a web server component and Electron is a client app framework. I don't see how they fit together. Can you describe your use case?

**Comment by dee342** [comment]
I am trying to do a SSO to a Windows machine.  Here are the high level requirements:

1.User should not have to enter user name and password into Electron app after having successfully logged onto the machine.
2.	User should be able to access parts of the api based on the LDAP groups they have been added to.

I can access the username and usergroups using Express, NodeJS and NodeSSPI.  However, when I try to add Electron I get an error message.  I would like to use NodeSSPI (because it works) without having to go through Express.  Here is my main.js.

var express = require( 'express' );
var nodeSSPI = require( 'node-sspi' );
var server = express();
server.use(
    function (req, res, next){
        var nodeSSPIObj = new nodeSSPI(
            {
                retrieveGroups: true,
            }
        );
        nodeSSPIObj.authenticate(
            req, res, function (err){
                res.finished || next();
            }
        );
    }
);
server.use(
    function (req, res, next){
        var out = 'Hello ' + req.connection.user + '! You belong to following groups:<br/><ul>';
        if(req.connection.userGroups) {
            for (var i in req.connection.userGroups) {
                out += '<li>' + req.connection.userGroups[i] + '</li><br/>\n';
            }
        }
        out += '</ul>';
        res.send( out );
    }
);
// Start server
var user = process.env.USERNAME;
var port = process.env.PORT || 3001;
server.listen(
    port, function (){
        console.log( 'User \"%s\" starting express server', user );
        console.log( 'Express server listening on port %d in %s mode', port, server.get( 'env' ) );
    }
);

**Comment by staskorz** [comment]
@dee342 , if it's for security reasons, then performing **authentication on client-side** is a **no-go**, as the user in control of the client machine can temper with your app to pose as whoever she wants.

If, on the other hand, all you need is to determine the currently logged in user, you could just read the Windows environment variable named `USERNAME`. At this stage you could use an `npm` package such as [`node-activedirectory`](https://github.com/gheeres/node-activedirectory) to determine the AD group membership.

**Comment by dee342** [comment]
@staskorz, Hi, it's for security reasons.  Do you have any ideas on what else I could use?  Thanks.

**Comment by staskorz** [comment]
Hi @dee342 , if the resource(s) you are trying to secure are located on the client machine, then you should probably rethink the concept. Whatever is on the client machine could potentially be accessed by the local user, _almost_ regardless of the measures taken.

Generally speaking, the sensitive resources should reside on the server. In this case, as users have no _uncontrolled_ access to the server, the `NodeSSPI` package could be safely used _on the server side_.

**Comment by abbr** [comment]
Even though NodeSSPI doesn't depend on Express, it depends on Windows and NodeJS. The latter further depends on V8. Because Electron has it's own V8 dependency, it is not compatible with NodeJS therefore unable to run NodeSSPI.

Ref: https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md
