### ISSUE TITLE
Running NodeSSPI as a module export?

### ISSUE THREAD

**Issue by BrianJVarley** [abbr/NodeSSPI#32]
@arashTaher  @abbr  I recently tried to port the SSPI authenticate method to a module export instead of hosting on a server. But this doesn't seem to play well with the API giving the following errors:

```
client:75 ./~/node-sspi/index.js
Module not found: Error: Cannot resolve module 'fs'  
```

This was the implementation that I tried where the auth module was imported to a component and invoked via auth.authenticate() in the auth.js file:

```
var nodeSSPI = require('node-sspi');
var nodeSSPIObj = new nodeSSPI({ retrieveGroups: true });

module.exports = {

  express: require('express'),
  nodeSSPI: nodeSSPI,
  nodeSSPIObj: nodeSSPIObj,
  authenticate: function () {
    nodeSSPIObj.authenticate(req, res, function(err){
      var ntUser = req.connection.user;
      return ntUser;
    })
  }
    
}
```

If this pattern is not possible. Is it possible to run the server example shown on your repository in a remote server instead of localhost? I'm asking this as I'm wondering if I send a request from my browser to the remote server can it still guess my username or will it simply return the username of the remote machine?

Thanks!

Brian

**Comment by abbr** [comment]
nodeSSPI has to be run by node which provides `fs` module. I guess you are trying to run nodeSSPI in browser and is not supported.

**Comment by BrianJVarley** [comment]
@abbr yes I was trying to run via the client because I didn't understand the implementation. I fixed the solution by migrating this nodeSSPI api call to our express server on the backend. I then passed the http request to this server and extracted the nt info from that.
