### ISSUE TITLE
Getting full user credentials

### ISSUE THREAD

**Issue by iyever** [abbr/NodeSSPI#36]
I need to implement Windows SSO without asking users to login. I think I can use NodeSSI to get the user name from their windows box and then send the info to LDAP for further authentication and the user info I need for the application, but I would need the user's password to make the LDAP call. How can I get the password from NodeSSI?

**Comment by abbr** [comment]
NodeSSPI doesn't get user name from their windows box. Browser does.
Also, under NTLM protocol user's password is never passed to NodeSSPI, only the password hash. So what you are trying to achieve is infeasible.
