### ISSUE TITLE
Session expiring while closing the browser window

### ISSUE THREAD

**Issue by rampatina** [abbr/NodeSSPI#38]
I am using node-sspi to authenticate with windows credentials for the MEAN application. Below is the code I am using:
`var server = require('http').createServer(app);
// Autorization part

app.use(function (req, res, next) {
  var nodeSSPI = require('node-sspi');
  var nodeSSPIObj = new nodeSSPI({
    domain: 'XX'
  });
  nodeSSPIObj.authenticate(req, res, function(err){
    res.finished || next();
  });
});
server.listen(port, function(){
    console.log('Server started on port '+port);
}`

The problem is, the authentication is working awesome but when I closes the browser and reopen it then it was again prompting for the username/password (Tried in IE, Chrome and Firefox). Here we want to preserve the sessions until we deletes the browser history or for some extent time period.

And one more thing, While deleting browser history and cookies the application should prompt for the credentials on page refresh. This was working well with Chrome but not with IE and Firefox. Is this known issue.

Can you please help me to overcome the above issues.

Thanks,
Rambabu.

**Comment by abbr** [comment]
Windows authentication doesn't support "remember me" feature. You have to use web form login if that's required and NodeSSPI is the wrong module.
