### ISSUE TITLE
Custom login page.

### ISSUE THREAD

**Issue by dlinx** [abbr/NodeSSPI#4]
How to implement an custom login page?

**Comment by waugusto** [comment]
Hello,

I have a similar scenario. Where I have a user filled form which I would like to compare the entries with the local machine if it exists.

Ex:

`app.post("/auth", function(req, res) {  
  
  var maquinaLocal  = req.connection.user;
  var userID = req.connection.userSid;
  var nomeMaquina = maquinaLocal.substr(0, maquinaLocal.indexOf("\\"));
  var usuario = nomeMaquina + "\\" + req.body.usuario ;
  var senha = req.body.senha;

  console.log('-----------------------------');
  console.log('Retorno da query SPPI: ' + maquinaLocal);
  console.log('Nome da maquina: ' + nomeMaquina);
  console.log('Nome do usuario: ' + usuario);
  //console.log(senha);
  console.log('-----------------------------');

  if (usuario == maquinaLocal  ) {
    console.log('Logado com sucesso: ' + usuario)
    res.redirect('http://uol.com.br');
  } else {
    console.log('Usuário ou senha invalidos')
    res.redirect('/');
  }
  console.log('-----------------------------');
});`
