### ISSUE TITLE
Error while installing NodeSSPI module

### ISSUE THREAD

**Issue by sunilravela** [abbr/NodeSSPI#40]
I am not able to install  NodeSSPI module, while the other modules are properly installed and working fine. Attached is the error log for reference

[Node SSPI error.txt](https://github.com/abbr/NodeSSPI/files/1158662/Node.SSPI.error.txt)

**Comment by abbr** [comment]
I tried same version of nodejs as yours and cannot reproduce. What if you try again on another pc or folder?
