### ISSUE TITLE
User undefined when index.js not in the same machine with Active Directory machine

### ISSUE THREAD

**Issue by ChucTruong** [abbr/NodeSSPI#46]
Hi guys, 

I've got a problem with the environment for this module.

When I run this module on the same machine with Active Directory, it's worked. But when I run this module on difference server that doesn't have the AD (but still in the same AD domain). It's not worked. 

Could you guys please help me on this?

**Comment by abbr** [comment]
What's the output if you run example code on "server that doesn't have the AD"?

**Comment by ChucTruong** [comment]
Besides AD and server that doesn't have the AD, there is a different machine for client (still in the same AD domain). After I run node index.js in server that doesn't have the AD, I open http://chuctruong:3000 (chuctruong is computer name of the server) and the output is:
Hello undefined! Your sid is undefined and you belong to following groups:

**Comment by abbr** [comment]
Cannot reproduce case 2. Make sure you login with a domain account rather than local account in case 2. Also to clarify terminology, all MS Windows server have AD installed. I interpret what you mean by 'Server that doesn't have the AD' as 'server not an AD controller'.
