### ISSUE TITLE
Using node-sspi acting as a client?

### ISSUE THREAD

**Issue by StefanScherer** [abbr/NodeSSPI#49]
First thanks for this Node module, it helps me get rid of keytab files :-)
In another project I would like to use Node.js acting as a client application using NTLM.
The Node modules I found so far want a user + password.
Do you know of a module that uses the Windows API to to NTLM on client side to form an HTTP request for the current user?
Is it possible to do this with this node-sspi module?
Can it be enhanced to do that?
Thanks for any pointer.

**Comment by abbr** [comment]
duplicated #10.

**Comment by StefanScherer** [comment]
Thank you for the pointer.
