### ISSUE TITLE
Remember user login and password?

### ISSUE THREAD

**Issue by manking99** [abbr/NodeSSPI#50]
Hello!
How to save the last login and password with which the user logged on?
So that it is then displayed with asterisks for this user?
![image](https://user-images.githubusercontent.com/5559817/36898105-7876b9de-1e2a-11e8-834c-69a4ebb0b258.png)

	```
	var nodeSSPI = require('node-sspi');
		var nodeSSPIObj = new nodeSSPI({
			offerSSPI: false,
			offerBasic : true,
			maxLoginAttemptsPerConnection : 8, 
			retrieveGroups: true
		});
```

**Comment by abbr** [comment]
This is a browser feature.
