### ISSUE TITLE
Specify Session Time

### ISSUE THREAD

**Issue by CrisIzag** [abbr/NodeSSPI#52]
Hi, I am working on an application and I am using node-sspi for user authentication. The problem that I am facing is that after I certain period of time, say 20-30 min, I am prompted to re-authenticate. I was wondering if there is a way that I can specify the session timeout so that the session stays active for 24 hours if the user keeps their browser open?

**Comment by abbr** [comment]
NodeSSPI tracks authenticated user info in connection, hence the lifespan is the same as connection and there is no configurable timeout. Usually lifespan is much shorter than 20min by my test. If you want customizable timeout, you can add a session middleware, which is typically cookie based.
