### ISSUE TITLE
Problem with IE

### ISSUE THREAD

**Issue by joker63** [abbr/NodeSSPI#54]
I have a problem with Internet Explorer. I use ReactJS from the client to request a node.js, then proxy to api.
If the component is enabled, then part of the requests are not proxy correctly.
How authorizations work:
1. The user goes to '/'
2. If the JWT token is not present or it is not valid, the redirect to / domain
3. / domain turns on your component, obtains data about users, makes a request in the API to get a JWT token.
3.a If the user is denied access, redirect to / login, for authorization. I enter login and password. I click the Log In button and get 400 error from the API. I do not change the data, I click on enter, answer 200.

code 400 https://prnt.sc/j13jiz
code 200 https://prnt.sc/j13job

There are errors in other requests.
Other browsers work fine.

**Comment by abbr** [comment]
How do you know code 400 is generated by NodeSSPI?
