### ISSUE TITLE
Chrome/Edge return undefined for user

### ISSUE THREAD

**Issue by JLuboff** [abbr/NodeSSPI#56]
I am using NodeSSPI as path specific middleware. To do so, I have
```
const authUser = (req, res, next) => {
  const nodeSSPIObj = new NodeSSPI({
    domain: 'myDomain',
  });

  nodeSSPIObj.authenticate(req, res, (err) => {
    if (err) throw err;
    return res.finished || next();
  });
};
```
With my routes looking like so 
```
app.route('/').get(authUser, (req, res) => ...
```
This does work, however, here lies the issue. With Firefox, `req.connection.user` is defined right away. With Chrome and Edge it is first `undefined` but after 2-3 attempts it will return the user (no additional interaction by the user or code). If using the example code, it works fine as `res.send` appears to wait until `user` is defined (but you can see via `console.log` that `user` still takes time to be defined in Chrome/Edge). However, in my code as I'm needing `user` right away, it causes errors. To remedy, I have implemented another middleware function
```
const isAuthenticated = (req, res, next) => {
  if (req.connection.user) {
    return next();
  }
};
```
And the route 
```
app.route('/').get(authUser, isAuthenticated, (req, res) => ...
```

So while everything is working now, I'm wondering if there's a reason for this or if there is another solution? 
Thanks!

**Comment by retryW** [comment]
I'm also having an issue where Chrome and Edge are coming up as undefined user, with no groups.
This is happening even using the default code from the README.md.
Mine does not start working after a few attempts though.

However upon browsing with IE, it works flawlessly. 

Problem is our primary browser is Chrome, and the version of IE we run on this contract doesn't properly support my code. So if anyone knows how to fix this issue, it'd be greatly appreciated.

**Comment by JLuboff** [comment]
> 
> 
> I'm also having an issue where Chrome and Edge are coming up as undefined user, with no groups.
> This is happening even using the default code from the README.md.
> Mine does not start working after a few attempts though.
> 
> However upon browsing with IE, it works flawlessly.
> 
> Problem is our primary browser is Chrome, and the version of IE we run on this contract doesn't properly support my code. So if anyone knows how to fix this issue, it'd be greatly appreciated.

Have you tried implementing it the way I did? If you're using the README method of global middleware (app.use(..)), you may want to try adding 
```
if (req.connection.user) {
    return next();
  }
```
inside somewhere

**Comment by PowrSlave** [comment]
> > I'm also having an issue where Chrome and Edge are coming up as undefined user, with no groups.
> > This is happening even using the default code from the README.md.
> > Mine does not start working after a few attempts though.
> > However upon browsing with IE, it works flawlessly.
> > Problem is our primary browser is Chrome, and the version of IE we run on this contract doesn't properly support my code. So if anyone knows how to fix this issue, it'd be greatly appreciated.
> 
> Have you tried implementing it the way I did? If you're using the README method of global middleware (app.use(..)), you may want to try adding
> 
> ```
> if (req.connection.user) {
>     return next();
>   }
> ```
> inside somewhere

Could you be more specific? Are you implying that return next() should appear within the nodeSSPIObj.authenticate method or in the app.use() middelware that outputs the user groups?

**Comment by JLuboff** [comment]
I was meaning inside the nodeSSPIObj.authenticate method. Or perhaps setting it as the next app.use()
```
app.use((req, res, next) => {
  if (req.connection.user) {
    return next();
  }
})
```
You'd have to test it to see if it would work.

**Comment by retryW** [comment]
> > I'm also having an issue where Chrome and Edge are coming up as undefined user, with no groups.
> > This is happening even using the default code from the README.md.
> > Mine does not start working after a few attempts though.
> > However upon browsing with IE, it works flawlessly.
> > Problem is our primary browser is Chrome, and the version of IE we run on this contract doesn't properly support my code. So if anyone knows how to fix this issue, it'd be greatly appreciated.
> 
> Have you tried implementing it the way I did? If you're using the README method of global middleware (app.use(..)), you may want to try adding
> 
> ```
> if (req.connection.user) {
>     return next();
>   }
> ```
> inside somewhere

This doesn't make much sense honestly.
The authenticate method is already going to the next middleware (which is where the groups are printed out and the response is sent).  I'm receiving the response, however it's printing as undefined in Chrome/Edge (it's doing the same in my custom implementation). 

In IE, it works flawlessly.

I'm about to install Wireshark and Fiddler on the work machine so I can try debug what's happening to the traffic in Chrome.

**Comment by JLuboff** [comment]
I honestly don't understand the behavior either and that's why I went with the workaround I did. Please do report back if you find a better solution.

**Comment by retryW** [comment]
> I honestly don't understand the behavior either and that's why I went with the workaround I did. Please do report back if you find a better solution.

When using your workaround I have the exact same behavior. Undefined in Chrome, works perfectly in IE.

**Comment by JLuboff** [comment]
It may only work with how I have it (route defined middleware), as I know it works that way. It still gets multiple undefined from Chrome/Edge but doesn't continue to the route until the user is authenticated.

**Comment by retryW** [comment]
So I did some packet capture.  It appears the auth header isn't being sent in the initial request when using Chrome, but after receiving the 401, it then sends the auth header in the second req, however by that time the server sends back a normal response.

I'm fairly new when it comes to web development / analyzing web traffic.  So I'll post the captures below, and if anyone can give some insight into what's happening, it'd be greatly appreciated.

IE first req/res
![ie_1](https://user-images.githubusercontent.com/39615132/50801063-47c91400-1337-11e9-98a6-3eab9cabc4cc.PNG)

IE second req/res  (successfully responds and AD details are displayed)
![ie_2](https://user-images.githubusercontent.com/39615132/50801069-4c8dc800-1337-11e9-81e8-acb643c0b481.PNG)

IE auth for first req/res
![ie_auth_1](https://user-images.githubusercontent.com/39615132/50801074-5283a900-1337-11e9-9611-5078c483b0e1.PNG)

IE auth for second req/res
![ie_auth_2](https://user-images.githubusercontent.com/39615132/50801082-57e0f380-1337-11e9-9b83-0f84f5ca842b.PNG)

Chrome first req/res
![chrome_1](https://user-images.githubusercontent.com/39615132/50801093-5d3e3e00-1337-11e9-85c8-78217a1fcb90.PNG)

Chrome second req/res (sends response but AD details show as 'undefined')
![chrome_2](https://user-images.githubusercontent.com/39615132/50801097-60392e80-1337-11e9-9f1e-be3fbf80ca23.PNG)

Chrome auth for first req/res
![chrome_auth_1](https://user-images.githubusercontent.com/39615132/50801103-63341f00-1337-11e9-9543-df1c6ec1990b.PNG)

Chrome auth for second req/res
![chrome_auth_2](https://user-images.githubusercontent.com/39615132/50801105-662f0f80-1337-11e9-913d-5c0f75284571.PNG)

**Comment by retryW** [comment]
So I figured out the issue (in my case at least).

At my department there is registry whitelisting in Chrome as to what addresses can use Negotiate authentication.  Upon adding my machine to the following keys and restarting Chrome, it worked perfectly:
- HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome\AuthNegotiateDelegateWhitelist
- HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome\AuthServerWhitelist

Thankfully, the server this is intended to sit on is already whitelisted, it's just my local machine wasn't obviously.

**Comment by PowrSlave** [comment]
> I was meaning inside the nodeSSPIObj.authenticate method. Or perhaps setting it as the next app.use()
> 
> ```
> app.use((req, res, next) => {
>   if (req.connection.user) {
>     return next();
>   }
> })
> ```
> You'd have to test it to see if it would work.

I tried your initial post technique as well as taking the standard example code and adding this app.use and the problem persist. I am not able to implement the solution you found. Could you post what you are doing so I can see what I am missing? I appreciate the theoretical talk and snippets, but I'd like to see a working model.

**Comment by PowrSlave** [comment]
> So I figured out the issue (in my case at least).
> 
> At my department there is registry whitelisting in Chrome as to what addresses can use Negotiate authentication. Upon adding my machine to the following keys and restarting Chrome, it worked perfectly:
> 
> * HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome\AuthNegotiateDelegateWhitelist
> * HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome\AuthServerWhitelist
> 
> Thankfully, the server this is intended to sit on is already whitelisted, it's just my local machine wasn't obviously.

Does this really solve the problem though? If every user needs to do this on the client side?

**Comment by JLuboff** [comment]
With recent projects I've changed my approach slightly. I have the two following middlewares: 
```
export const authenticateUser: RequestHandler = (req, res, next) => {
//Checks if session exists, if so, checks if person object exists. I store
// certain information in the person object (username, email, etc)
  if (req.session && req.session.person) {
    return next();
  }
// If person does not exist in session, authenticate
  const nodeSSPIObj = new NodeSSPI({
    domain: process.env.DOMAIN,
    retrieveGroups: true
  });
  nodeSSPIObj.authenticate(req, res, (err: any) => {
    if (err) throw err;
    return res.finished || next();
  });
};
```
This is the first middleware to be accessed. To avoid bombarding the domain control, I check if the user exists already in the session.
```
export const isAuthenticated: RequestHandler = async (req, res, next) => {
  if (req.session && req.session.person) {
    return next();
  }
if (req.connection.user) {
 DoStuff 
}
```
This is the next middleware accessed after the prior function. Again, checks if person exists in the session, if so, `return next()`. For myself, this saves unnecessary database queries.  Otherwise, checks if the user exists on `req.connection`, if so perform certain actions. If not, it doesn't pass `next()` until the user or person exists.

Within my app entry file 
```
app.use(authenticateUser);
app.use(isAuthenticated);
app.use(routes);
```

This works in FF, Chrome, and Edge. Didn't test this way within IE. As I have a working solution, I'm going to close the issue. I may create a PR for the Readme to include this information....
