### ISSUE TITLE
Anonymous logins

### ISSUE THREAD

**Issue by pr0gramar** [abbr/NodeSSPI#6]
If user hits enter on the username/password dialog without entering credentials, node-sspi logs in user as Anonymous, is there a way to disable anonymous logins?

Also, once user has been authenticated as anonymous, I see no way of clearing this.
Is there a way to re-authenticate?

**Comment by abbr** [comment]
Thanks for the report. I can reproduce the bug and will provide a fix in a few days. I also found node-sspi may  pass auth but req.connection.user is undefined if user hit cancel on the dialog. If this is an urgent issue, you can set option `authoritative` to *false*, then add some validation code in downstream middleware.

**Comment by abbr** [comment]
Fixed in node-sspi@0.1.8.
