### ISSUE TITLE
401 Header Being Sent to not AD Devices Triggering Login Prompt...

### ISSUE THREAD

**Issue by PowrSlave** [abbr/NodeSSPI#63]
I'm using the out of the box, unchanged express example from the repo doc and it works flawlessly on a few different AD accounts I have tested it with (using Chrome). Responds back with and outputs groups that each account is a part of.

**The problem is that if I reach out to my-server:3000 from a device that is not part of active directory, the 401 header being sent triggers the default sign in prompt.** 

I've done some searching, but haven't found a way to prevent this sign in prompt from firing. I have only tested in Chrome and IE11 thus far. The behavior is consistent in each. What should I do about this?

**Comment by abbr** [comment]
Expected behavior. For non-ad devices, you have to manually enable integrated windows authentication for your site domain, usually by adding the domain to trusted intranet zone.
