### ISSUE TITLE
Memory leak NodeSSPI 0.2.5

### ISSUE THREAD

**Issue by sagitsofan** [abbr/NodeSSPI#67]
**OS**: Windows Server 2016 Standart
**Node JS**: 10.15.3 LTS

I noticed in my Node server whenever i used the SSPI as a middleware in Express i got a memory leak after a while when the server is running and bombed with multiple request.
Has any one experienced the same ?

**This is the error:**
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
node::DecodeWrite
 2: node_module_register
 3: v8::internal::FatalProcessOutOfMemory
 4: v8::internal::FatalProcessOutOfMemory
 5: v8::internal::Factory::NewFixedArray
 6: v8::internal::Dictionary<v8::internal::SeededNumberDictionary,v8::internal::SeededNumberDictionaryShape>::AtPut
 7: v8::internal::Dictionary<v8::internal::SeededNumberDictionary,v8::internal::SeededNumberDictionaryShape>::AtPut
 8: v8::internal::Dictionary<v8::internal::SeededNumberDictionary,v8::internal::SeededNumberDictionaryShape>::AtPut
 9: v8::internal::Dictionary<v8::internal::SeededNumberDictionary,v8::internal::SeededNumberDictionaryShape>::AtPut
10: unibrow::LineTerminator::Is
11: unibrow::LineTerminator::Is
12: unibrow::LineTerminator::Is
13: unibrow::LineTerminator::Is
14: v8::ObjectTemplate::NewInstance
15: v8::ObjectTemplate::NewInstance
16: 00007FFB04067EC9
17: 00007FFB04068B65
18: 00007FFB04061DF6

**This is the code that i used, when i disabled it every thing is working propertly:**

```
initSSPI = () => {
   
    return function (req, res, next) {
      res.setHeader('www-authenticate', 'NTLM');

      const nodeSSPIObj = new nodeSspi({
        retrieveGroups: true
      })

      nodeSSPIObj.authenticate(req, res, (err) => {
        res.finished || next()
      })
    }
  }
```

What could make this memory leak in the Node SSPI package?

**Comment by abbr** [comment]
What if setting retrieveGroups to false?

**Comment by sagitsofan** [comment]
Also tried to just no passed the `retrieveGroups` param into the constructor and still memory leak.

**Comment by sagitsofan** [comment]
![image](https://user-images.githubusercontent.com/1827994/56138843-5c552200-5fa0-11e9-82c2-d1394d67f246.png)

**Comment by alana1** [comment]
Hello, is this issue resolve in the latest version?

**Comment by sagitsofan** [comment]
Seems like that in node 12 and latest node-sspi issue has been resolved
