### ISSUE TITLE
Cannot install with Node 12.4

### ISSUE THREAD

**Issue by steelleg** [abbr/NodeSSPI#69]
npm install node-sspi

When I try it with Node 10.16 everything works fine.
With 12.4 it tries to build node-sspi looking for python, gyp and visual studio and fails.

**Comment by ahallicks** [comment]
This is the same as https://github.com/abbr/NodeSSPI/issues/58 - just needs the node 12 bin adding, if possible, @abbr

**Comment by sbeck1982** [comment]
I have the same issue, but as I was looking into the source code I found out that some classes were deprecated in v8 library with node 12 (bearking change) which will require some work to make this running again. Unfortunatelly, I am not familiar with V8 so I cannot create a pull request. This is a great library and I hope it will be compatible with node 12 soon.

**Comment by abbr** [comment]
Relates to #73.

**Comment by abbr** [comment]
fixed in node-sspi@0.2.6
