### ISSUE TITLE
Crash on login DeleteSecurityContext in NodeSSPI/src/NodeSSPI.cpp

### ISSUE THREAD

**Issue by Madnikulin50** [abbr/NodeSSPI#74]
void CleanupAuthenicationResources(Handle<Object> conn
	, PCtxtHandle pSvrCtxHdl = NULL)
{
	try {
		if (pSvrCtxHdl && pSvrCtxHdl->dwUpper > 0 && pSvrCtxHdl->dwLower > 0) {
			sspiModuleInfo.functable->DeleteSecurityContext(pSvrCtxHdl);
			pSvrCtxHdl->dwUpper = pSvrCtxHdl->dwLower = 0;

**Comment by abbr** [comment]
Evidence?
