### ISSUE TITLE
SSPI only works in Chrome

### ISSUE THREAD

**Issue by AO19** [abbr/NodeSSPI#78]
I have implemented the library in my project, it works perfect in Chrome.
I also added the npm package "activedirectory" to lookup the users in my AD.

But with Firefox, a login window pops up. It requires authentication.

Why does is work without a prompt in Chrome, but not in Firefox?

**Comment by fallwest** [comment]
With Firefox, go to about:config and change the following properties (use your own URL):
network.automatic-ntlm-auth.trusted-uris | http://localhost
network.negotiate-auth.delegation-uris | http://localhost
network.negotiate-auth.trusted-uris | http://localhost

Restart Firefox and voilà. Note: you may actually need to provide your credentials in the login box the first time.
