### ISSUE TITLE
fatal error C1083: Cannot open include file: 'atlenc.h'

### ISSUE THREAD

**Issue by PowrSlave** [abbr/NodeSSPI#79]
I was unsuccessful in getting nodeSSPI to install with Node V12.x, so I went back to 10.4.0 (which was the next minor version beyond 10.3.0 which is what my app was running on prior).

in Node 10.4.0, when attempting to install NodeSSPI, I get the following error:

fatal error C1083: Cannot open include file: 'atlenc.h': No such file or directory (compiling source file ..\src\NodeSSPI.cpp) [C:\Users\johnstza\htdocs\NodeSSPI\build\NodeSSPI.vcx
proj]

I have no idea what is going on. Has anyone seen this?

**Comment by abbr** [comment]
Which NodeSSPI version and how did you download?

**Comment by wabreisch** [comment]
For what it's worth, I was getting this same issue running Node v12.13.1 and NodeSSPI v0.2.5. My issue was resolved by updating NodeSSPI to v0.2.7 and running a clean `npm install`.
