### ISSUE TITLE
nodejs 14.x Support

### ISSUE THREAD

**Issue by Talaar** [abbr/NodeSSPI#83]
Hi there,

thanks for this great module but can you add nodejs 14.x support?

When i try to install then came this:
`Warning: Missing input files:                              
d:\WEB\tests\sspi\node_modules\node-sspi\build\..\src\*.cpp
d:\WEB\tests\sspi\node_modules\node-sspi\build\..\src\*.h`

**Comment by abbr** [comment]
v0.2.8 added nodejs 14 support.
