### ISSUE TITLE
Authenticate fails when behind IIS reverse-proxy

### ISSUE THREAD

**Issue by DanBrk** [abbr/NodeSSPI#95]
The client sends 'Negotiate' authorization header. 
On IIS site 'Windows Authentication' is enabled and I can see in the IIS logs that the user has been authenticated.
The node service is behind UrlRewrite reverse proxy

The problem is that authenticate fails and returns 'Login aborted'
When the client is connected directly without the reverse proxy the authentication succeed.

I am using node-sspi "0.2.8", NodeJs version 12.21 , Windows Server 2016.

Is there any way to see more detailed information about the error ?
Any idea why the authenticate fails behind IIS ?

**Comment by abbr** [comment]
This site is for reporting NodeSSPI issues, not for troubleshooting your infrastructure layout issues. Besides, it's not a valid NodeSSPI use case.
